Standardize the code by changing postgre, postgresql, etc. to gaussdb.

diff --git a/cmd/gaussdb_exporter/tests/test-smoke b/cmd/gaussdb_exporter/tests/test-smoke
--- a/cmd/gaussdb_exporter/tests/test-smoke
+++ b/cmd/gaussdb_exporter/tests/test-smoke
@@ -1,5 +1,5 @@
 #!/bin/bash -x
-# Basic integration tests with postgres. Requires docker to work.
+# Basic integration tests with gaussdb. Requires docker to work.
 
 SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
@@ -12,15 +12,15 @@ DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 METRICS_DIR=$(pwd)
 
 # Read the absolute path to the exporter
-postgres_exporter="$1"
+gaussdb_exporter="$1"
 test_binary="$2"
-export POSTGRES_PASSWORD=postgres
+export POSTGRES_PASSWORD=gaussdb
 exporter_port=9187
 
-echo "Exporter Binary: $postgres_exporter" 1>&2
+echo "Exporter Binary: $gaussdb_exporter" 1>&2
 echo "Test Binary: $test_binary" 1>&2
 
-[ -z "$postgres_exporter" ] && echo "Missing exporter binary" && exit 1
+[ -z "$gaussdb_exporter" ] && echo "Missing exporter binary" && exit 1
 [ -z "$test_binary" ] && echo "Missing test binary" && exit 1
 
 cd "$DIR" || exit 1
@@ -33,7 +33,7 @@ VERSIONS=( \
     11 \
 )
 
-wait_for_postgres(){
+wait_for_gaussdb(){
     local container=$1
     local ip=$2
     local port=$3
@@ -49,15 +49,15 @@ wait_for_postgres(){
     
     local wait_start
     wait_start=$(date +%s) || exit 1
-    echo "Waiting for postgres to start listening..."
+    echo "Waiting for gaussdb to start listening..."
     while ! docker exec "$container" pg_isready --host="$ip" --port="$port" &> /dev/null; do
         if [ $(( $(date +%s) - wait_start )) -gt "$TIMEOUT" ]; then
-            echo "Timed out waiting for postgres to start!" 1>&2
+            echo "Timed out waiting for gaussdb to start!" 1>&2
             exit 1            
         fi
         sleep 1
     done
-    echo "Postgres is online at $ip:$port"
+    echo "GaussDB is online at $ip:$port"
 }
 
 wait_for_exporter() {
@@ -74,16 +74,16 @@ wait_for_exporter() {
     echo "Exporter is online at localhost:$exporter_port"
 }
 
-smoketest_postgres() {
+smoketest_gaussdb() {
     local version=$1
-    local CONTAINER_NAME=postgres_exporter-test-smoke
+    local CONTAINER_NAME=gaussdb_exporter-test-smoke
     local TIMEOUT=30
-    local IMAGE_NAME=postgres
+    local IMAGE_NAME=gaussdb
     
     local CUR_IMAGE=$IMAGE_NAME:$version
     
     echo "#######################"
-    echo "Standalone Postgres $version"
+    echo "Standalone GaussDB $version"
     echo "#######################"
     local docker_cmd="docker run -d -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD $CUR_IMAGE"
     echo "Docker Cmd: $docker_cmd"
@@ -92,13 +92,13 @@ smoketest_postgres() {
     standalone_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_NAME)
     # shellcheck disable=SC2064
     trap "docker logs $CONTAINER_NAME ; docker kill $CONTAINER_NAME ; docker rm -v $CONTAINER_NAME; exit 1" EXIT INT TERM
-    wait_for_postgres "$CONTAINER_NAME" "$standalone_ip" 5432
+    wait_for_gaussdb "$CONTAINER_NAME" "$standalone_ip" 5432
 
     # Run the test binary.
-    DATA_SOURCE_NAME="postgresql://postgres:$POSTGRES_PASSWORD@$standalone_ip:5432/?sslmode=disable" $test_binary || exit $?
+    DATA_SOURCE_NAME="gaussdb://gaussdb:$POSTGRES_PASSWORD@$standalone_ip:5432/?sslmode=disable" $test_binary || exit $?
 
     # Extract a raw metric list.
-    DATA_SOURCE_NAME="postgresql://postgres:$POSTGRES_PASSWORD@$standalone_ip:5432/?sslmode=disable" $postgres_exporter \
+    DATA_SOURCE_NAME="gaussdb://postgres:$POSTGRES_PASSWORD@$standalone_ip:5432/?sslmode=disable" $postgres_exporter \
         --log.level=debug --web.listen-address=:$exporter_port &
     exporter_pid=$!
     # shellcheck disable=SC2064
@@ -147,9 +147,9 @@ smoketest_postgres() {
     wait_for_postgres "$master_container" "$master_ip" 5432
     wait_for_postgres "$slave_container" "$slave_ip" 5432
     
-    DATA_SOURCE_NAME="postgresql://postgres:$POSTGRES_PASSWORD@$master_ip:5432/?sslmode=disable" $test_binary || exit $?
+    DATA_SOURCE_NAME="gaussdb://postgres:$POSTGRES_PASSWORD@$master_ip:5432/?sslmode=disable" $test_binary || exit $?
     
-    DATA_SOURCE_NAME="postgresql://postgres:$POSTGRES_PASSWORD@$master_ip:5432/?sslmode=disable" $postgres_exporter \
+    DATA_SOURCE_NAME="gaussdb://postgres:$POSTGRES_PASSWORD@$master_ip:5432/?sslmode=disable" $postgres_exporter \
         --log.level=debug --web.listen-address=:$exporter_port &
     exporter_pid=$!
     # shellcheck disable=SC2064
